spring:
  application:
    name:XT_Blog_S
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///xtblog_db
    username: root
    password: root


mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
  mapper-locations: classpath*:site/icefox/xt_blog_s/mapper/*.xml